name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup go 1.16
      uses: actions/setup-go@v2
      with:
        stable: false
        go-version: 1.16.0-beta1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
